-- Retrieve the total number of orders placed.

SELECT COUNT(ORDER_ID) AS TOTAL_ORDER
FROM ORDERS;

-- Calculate the total revenue generated from pizza sales.

SELECT ROUND(SUM(OD.QUANTITY * P.PRICE),2) AS TOTAL_SALES
FROM ORDER_DETAILS AS OD
JOIN PIZZAS AS P
ON P.PIZZA_ID = OD.PIZZA_ID;

-- Identify the highest-priced pizza.

SELECT PT.NAME,P.PRICE
FROM PIZZA_TYPES AS PT
JOIN PIZZAS AS P
ON PT.PIZZA_TYPE_ID = P.PIZZA_TYPE_ID
ORDER BY P.PRICE DESC
LIMIT 1;

-- Identify the most common pizza size ordered.

SELECT P.SIZE, COUNT(OD.ORDER_DETAIL_ID) AS ORDER_COUNT
FROM PIZZAS AS P 
JOIN ORDER_DETAILS AS OD
ON P.PIZZA_ID = OD.PIZZA_ID
GROUP BY P.SIZE
ORDER BY ORDER_COUNT DESC;

-- List the top 5 most ordered pizza types along with their quantities.

SELECT PIZZA_TYPES.NAME,
SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY
FROM PIZZA_TYPES
JOIN PIZZAS
ON PIZZA_TYPES. PIZZA_TYPE_ID = PIZZAS. PIZZA_TYPE_ID
JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME
ORDER BY QUANTITY DESC
LIMIT 5;

-- Join the necessary tables to find the total quantity of each pizza category ordered.

SELECT PIZZA_TYPES.CATEGORY,
SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY
FROM PIZZA_TYPES
JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZAS_TYPES.CATEGORY
ORDER BY QUANTITY DESC;

-- Group the orders by date and calculate the average number of pizzas ordered per day.

SELECT ROUND(AVG(QUANTITY),0) AS AVG_PIZZA_PER_DAY
FROM
(SELECT ORDERS.ORDER_DATE,
SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY
FROM ORDERS
JOIN ORDER_DETAILS
ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
GROUP BY ORDERS.ORDER_DATE) AS ORDER_QUANTITY;

-- Determine the distribution of orders by hour of the day.

SELECT HOUR(ORDER_TIME) AS HOUR, COUNT(ORDER_ID) AS ORDER_OF_COUNT
FROM ORDERS
GROUP BY HOUR(ORDER_TIME);

-- Determine the top 3 most ordered pizza types based on revenue.

SELECT PIZZA_TYPES.NAME,
SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE
FROM PIZZA_TYPES
JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS. PIZZA_TYPE_ID
JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME
ORDER BY REVENUE DESC
LIMIT 3;

-- Join relevant tables to find the category-wise distribution of pizzas.

SELECT CATEGORY, COUNT(NAME)
FROM PIZZAS_TYPES
GROUP BY CATEGORY;
